config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :users
  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/user.rb
class User < ActiveRecord::Base
   authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_to controller: 'users',action: 'show', id: current_user
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HelloWorld
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / Fonts and icons
    %link{:href => "http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons", :rel => "stylesheet", :type => "text/css"}/
  %body
    /
      <div>
      <p id="notice"><haml_loud> flash[:notice] </haml_loud></p>
      <p id="alert"><haml_loud> flash[:alert] </haml_loud></p>
      </div>
    = yield

app/views/user_sessions/_form.html.haml
= form_tag user_sessions_path, class: "form-wrapper", :method => :post do
  %h1 Login
  .form-item
    \&gt;
    \#{label_tag :email}
    %br/
    = text_field_tag :email
  .form-item
    = label_tag :password
    %br/
    = password_field_tag :password
  .button-panel.button
    = submit_tag "Login", :class => "button"
  .form-footer
    = link_to "新規登録の方はこちら", new_user_path
    / <p><a href="#">Forgot password?</a></p>

app/views/user_sessions/create.html.haml
%h1 UserSessions#create
%p Find me in app/views/user_sessions/create.html.erb

app/views/user_sessions/destroy.html.haml
%h1 UserSessions#destroy
%p Find me in app/views/user_sessions/destroy.html.erb

app/views/user_sessions/new.html.haml
= render 'form'

app/views/users/_form.html.haml
= form_for( @user, html: {class: "form-wrapper"} ) do |f|
  %h1 New User
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message
  .form-item
    = f.label :email
    %br/
    = f.text_field :email
  .form-item
    = f.label :password
    %br/
    = f.password_field :password
  .form-item
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  .button-panel
    = f.submit 'Create', class: "button"
  .form-footer
    = link_to "アカウントを既にお持ちの方はこちら", :login
    / <p><a href="#">Forgot password?</a></p>

app/views/users/edit.html.haml
%h1 Editing User
= render 'form'
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/index.html.haml
%br/
= link_to 'New User', new_user_path
%p#notice= notice
%h1 LP
-# %table
-#   %thead
-#     %tr
-#       %th Email
-#       %th{:colspan => "3"}
-#   %tbody
-#     - @users.each do |user|
-#       %tr
-#         %td= user.email
-#         %td= link_to 'Show', user
-#         %td= link_to 'Edit', edit_user_path(user)
-#         %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/new.html.haml
= render 'form'

app/views/users/show.html.haml
.wrapper
  .sidebar{"data-color" => "purple", "data-image" => "../assets/img/sidebar-1.jpg"}
    /
      Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"
      Tip 2: you can also add an image using data-image tag
    .logo
      %a.simple-text
        Hello-world
    .sidebar-wrapper
      %ul.nav
        %li
          %a{:href => "dashboard.html"}
            %i.material-icons dashboard
            %p Dashboard
        %li.active
          %a{:href => "./user.html"}
            %i.material-icons person
            %p User Profile
        %li
          %a{:href => "./table.html"}
            %i.material-icons content_paste
            %p Table List
        %li
          %a{:href => "./typography.html"}
            %i.material-icons library_books
            %p Typography
        %li
          %a{:href => "./icons.html"}
            %i.material-icons bubble_chart
            %p Icons
        %li
          %a{:href => "./maps.html"}
            %i.material-icons location_on
            %p Maps
        %li
          %a{:href => "./notifications.html"}
            %i.material-icons.text-gray notifications
            %p Notifications
        %li.active-pro
          %a{:href => "upgrade.html"}
            %i.material-icons unarchive
            %p Upgrade to PRO
  .main-panel
    %nav.navbar.navbar-transparent.navbar-absolute
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} Profile

        .collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            %li
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#pablo"}
                %i.material-icons dashboard
                %p.hidden-lg.hidden-md Dashboard

            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.material-icons person
                <span class="notification">5</span>
                %p.hidden-lg.hidden-md Notifications
              %ul.dropdown-menu
                %li
                  = link_to 'Edit', edit_user_path(@user)
                %li
                  = link_to "Logout", :logout, method: :post
                %li
                  %a{:href => "#"} You're now friend with Andrew
                %li
                  %a{:href => "#"} Another Notification
                %li
                  %a{:href => "#"} Another One

            %li
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#pablo"}
                %i.material-icons notifications
                %p.hidden-lg.hidden-md Profile

          %form.navbar-form.navbar-right{:role => "search"}
            .form-group.is-empty
              %input.form-control{:placeholder => "Search", :type => "text"}/
              %span.material-input
            %button.btn.btn-white.btn-round.btn-just-icon{:type => "submit"}
              %i.material-icons search
              .ripple-container
    .content
      .container-fluid
        .row
          .col-md-8
            .card
              .card-header{"data-background-color" => "purple"}
                %h4.title Edit Profile
                %p.category Complete your profile
              .card-content
                %form
                  .row
                    .col-md-5
                      .form-group.label-floating
                        %label.control-label Company (disabled)
                        %input.form-control{:disabled => "disabled", :type => "text"}/
                    .col-md-3
                      .form-group.label-floating
                        %label.control-label Username
                        %input.form-control{:type => "text"}/
                    .col-md-4
                      .form-group.label-floating
                        %label.control-label Email address
                        %input.form-control{:type => "email"}/
                  .row
                    .col-md-6
                      .form-group.label-floating
                        %label.control-label Fist Name
                        %input.form-control{:type => "text"}/
                    .col-md-6
                      .form-group.label-floating
                        %label.control-label Last Name
                        %input.form-control{:type => "text"}/
                  .row
                    .col-md-12
                      .form-group.label-floating
                        %label.control-label Adress
                        %input.form-control{:type => "text"}/
                  .row
                    .col-md-4
                      .form-group.label-floating
                        %label.control-label City
                        %input.form-control{:type => "text"}/
                    .col-md-4
                      .form-group.label-floating
                        %label.control-label Country
                        %input.form-control{:type => "text"}/
                    .col-md-4
                      .form-group.label-floating
                        %label.control-label Postal Code
                        %input.form-control{:type => "text"}/
                  .row
                    .col-md-12
                      .form-group
                        %label About Me
                        .form-group.label-floating
                          %label.control-label
                          %textarea.form-control{:rows => "5"}
                  %button.btn.btn-primary.pull-right{:type => "submit"} Update Profile
                  .clearfix
          .col-md-4
            .card.card-profile
              .card-avatar
                %a{:href => "#pablo"}
                  %img.img{:src => "../assets/img/faces/marc.jpg"}/
              .content
                %h6.category.text-gray CEO / Co-Founder
                %h4.card-title Alec Thompson
                %p.card-content
                  Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
                %a.btn.btn-primary.btn-round{:href => "#pablo"} Follow